--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/nicholass003/QuantumCrates
build-by-default: true
branches:
- master
- stable
projects:
  QuantumCrates:
    path: ""
    icon: "assets/icon.png"
...
