--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/nicholass003/QuantumCrates
build-by-default: true
branches:
- stable
projects:
  QuantumCrates:
    path: ""
    icon: "assets/icon.png"
    libs:
      - src: muqsit/InvMenu/InvMenu
        branch: pm5
        version: ^4.6.5
...
